# -*- coding: utf-8 -*-
"""open ai STT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BT3s8bTLOW9UYwrdVcjzLMXR8UvXBhyd
"""

!nvidia-smi

!pip install git+https://github.com/huggingface/transformers.git

!pip install git+https://github.com/huggingface/transformers -q

!wget -O audio.mp3 https://www.moviesoundclips.net/movies1/guardiansofthegalaxy/battery.mp3

from IPython.display import Audio,display
display(Audio('audio.mp3',autoplay=True))

from transformers import pipeline

whisper=pipeline('automatic-speech-recognition',model='openai/whisper-medium')

text=whisper('audio.mp3')

text